### ISSUE TITLE
Hosting Audrch on examples.jina.ai

### ISSUE THREAD

**Issue by alexcg1** [akshatdalton/Audrch#4]
Once I can get Audrch:

a) working
b) up and running with `docker-compose`
c) returning quality matches (untested yet since Streamlit issue)

I'd be happy to put it on examples.jina.ai for our community to play with if you like. We'll plug you obviously!

**Comment by akshatdalton** [comment]
@alexcg1 I have no problem with that, feel free to share it on any social media.
In the upcoming days, I will try to integrate Spotify dataset, so that it may look more cool to the users when they will search for similar songs.

**Comment by alexcg1** [comment]
Nice! Let me know when that's done - it'd be so much cooler then!

Is the dataset open btw?

**Comment by akshatdalton** [comment]
@alexcg1 
Dataset can be found here: https://www.kaggle.com/mrmorj/dataset-of-songs-in-spotify
There are some problems tho:
1. You need an access token to make the request to the API. (https://developer.spotify.com/console/get-track). It expires after a while.
2. The returned response from the API contains `preview_url` (which is the only playable url) and it is of 30 sec. But what I can do here is that use these `preview_url`s to train my model and search query from them and for each found match I can give users an API to open those matches in Spotify.
We can't find Spotify URLs with full song length because of licensing reasons.

**Comment by alexcg1** [comment]
Nifty! I'll give it a try next week

**Comment by akshatdalton** [comment]
@alexcg1, I found the `Spotipy` library which makes our work easy. Using it we don't need to worry about the access token but you need to set some environment variables (I have updated the `README` for the same). Try these new changes!
Here is the screencast of the new changes:

https://user-images.githubusercontent.com/67277428/150653834-1771b366-7754-4022-91a9-55039ae04405.mp4
